sonar.projectKey=Neofilisoft_AsterCorePhysics
sonar.organization=Neofilisoft

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=AsterCore Physics
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=AsterCore
